### ISSUE TITLE
Can cuda11.x, 30 series graphics card run?

### ISSUE THREAD

**Issue by AwakerLee** [comrados/jdsh#1]

**Comment by AwakerLee** [comment]
Why is it stuck in calculating MAP?

**Comment by comrados** [comment]
@AwakerLee no idea. As far as i remember i was running it on cuda 10.2.

BTW, you can try to use the code from original papers' repo:
https://github.com/KaiserLew/JDSH
https://github.com/zs-zhong/DJSRH
